import { customAlphabet } from 'nanoid';

const alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
const nanoId = customAlphabet(alphabet, 19)

export const generateId = (key: keyof typeof prefixes): string => {
  return prefixes[key] + nanoId()
}

export enum prefixes {
  Database = 'dbase_',
  Company = 'compy_',
  CompanyMapping = 'comap_',
  Project = 'projt_',
  Admin = 'adman_',
  AdminToken = 'admto_',
  AdminSession = 'admse_',
  AdminDevice = 'admde_',
  AdminActivity = 'admac_',
  ApiKey = 'apiky_',
  Role = 'roles_',
  Feature = 'featr_',
  Task = 'tasks_',
  ErrorLog = 'erlog_',
  User = 'users_',
  ApiIntegrationLog = 'apilo_',
  Token = 'tokde_',
  UserSession = 'usess_',
  UserActivity = 'usact_',
  UserDevice = 'user2_',
  LogoutUser = 'logus_',
  Category = 'cates_',
  CategoryHistory = 'cathi_',
  Group = 'group_',
  Microskill = 'micsk_',
  MicroskillHistory = 'mihis_',
  Challenge = 'chalg_',
  ChallengeHistory = 'chahy_',
  Question = 'qustn_',
  Answer = 'answe_',
  Skill = 'skill_',
  Context = 'conte_',
  Card = 'cards_',
  MediaResource = 'medre_',
  UserMicroskillHistory = 'usmih_',
  UserChallengeAttempt = 'uscha_',
  UserQuestionAnswer = 'usqua_',
  UserSpotLightResponse = 'usspo_',
  UserFeedback = 'usfes_',
  Announcement = 'annon_',
  Repository = 'repos_',
  Form = 'forms_',
  FormQuestion = 'forqu_',
  FormAnswer = 'foran_',
  UserForm = 'usefo_',
  UserFormAttempt = 'usfoa_',
  UserFormQuestionAnswer = 'usfoq_',
  PushNotification = 'pusno_',
  UserPushNotification = 'uspun_',
  CourseCategory = 'couca_',
  CourseType = 'cotyp_',
  Course = 'cours_',
  CourseEvent = 'couev_',
  TrainingLocation = 'tralo_',
  Training = 'trais_',
  Batch = 'batcs_'
}