export enum Subjects {
  CompanyCreated = 'company:created',
  CompanyUpdated = 'company:updated',
  CompanyDeleted = 'company:deleted',
  CompanyReactivated = 'company:reactivated',
  CompanyRuleCreated = 'companyRule:created',
  CompanyRuleUpdated = 'companyRule:updated',
  ProjectCreated = 'project:created',
  ProjectUpdated = 'project:updated',
  ProjectDeleted = 'project:deleted',
  ProjectReactivated = 'project:reactivated',
  ModuleCreated = 'module:created',
  ModuleUpdated = 'module:updated',
  ModuleDeleted = 'module:deleted',
  ModuleReactivated = 'module:reactivated',
  ChallengeCreated = 'challenge:created',
  ChallengeUpdated = 'challenge:updated',
  ChallengeDeleted = 'challenge:deleted',
  ChallengeReactivated = 'challenge:reactivated',
  UsersCreated = 'users:created',
  UsersUpdated = 'users:updated',
  UsersDeleted = 'users:deleted',
  UsersReactivated = 'users:reactivated',
}
